# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kartikey Grover
title: Data Scientist
email: kg458@cornell.edu
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Kartikey0412
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kg458@cornell.edu
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: Kartikey Grover
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# Google_scholar_username: Kartikey Grover

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-book
  url: https://scholar.google.com/citations?hl=en&user=hAt9TBwAAAAJ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: image/headshot_small copy.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a data scientist at Aetna, CVS Health and really interested in Healthcare to improve people's health. My work is centered around opportunity sizing from encouter and pharmacy data for improving medical cost savings in the form oh health campaigns targeting members most likely to benefit from the outreach programs. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Six Sigma Black Belt 
        link: https://docs.google.com/document/d/1JsqiwN35bfKNJT97pZnZG3DLK1x5rF08m-aK5hlSa1M/edit
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aetna, CVS Health
        link: https://www.aetna.com/health-care-professionals/newsletters-news/office-link-updates-december-2018/news-for-you-december-2018/together-for-you-aetna-cvs-health.html
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: Sept 2019 - Present
        #quote: >
         # Solving 21st century problems by diging holes and making game changing products 
        description: | # this will include new lines to allow paragraphs
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cornell University
        caption: 2015 - 2016
        sub_title: Master of Engineering Biomedical Engineering
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Poet
      - APA Pool Player
      - [biomechanics](https://www.youtube.com/watch?v=tVrNsXb3woA)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
